spring.application.name=gigshield-ai-api
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:6969/gigshield_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1691

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Data Seeding
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
